/*
 * MiniCloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package daemon

type EventMessage struct {
	Type string `json:"type,omitempty"`

	// The type of the event
	Action string `json:"action,omitempty"`

	// Timestamp of the event
	Time int32 `json:"time,omitempty"`

	Object EventMessageObject `json:"object,omitempty"`
}

// AssertEventMessageRequired checks if the required fields are not zero-ed
func AssertEventMessageRequired(obj EventMessage) error {
	if err := AssertEventMessageObjectRequired(obj.Object); err != nil {
		return err
	}
	return nil
}

// AssertRecurseEventMessageRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of EventMessage (e.g. [][]EventMessage), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseEventMessageRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aEventMessage, ok := obj.(EventMessage)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertEventMessageRequired(aEventMessage)
	})
}
