/*
 * MiniCloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package daemon

type EventsRequest struct {
	Type string `json:"type,omitempty"`

	Name string `json:"name,omitempty"`
}

// AssertEventsRequestRequired checks if the required fields are not zero-ed
func AssertEventsRequestRequired(obj EventsRequest) error {
	return nil
}

// AssertRecurseEventsRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of EventsRequest (e.g. [][]EventsRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseEventsRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aEventsRequest, ok := obj.(EventsRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertEventsRequestRequired(aEventsRequest)
	})
}
