/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package minicloud.client.api;

import minicloud.client.model.ApiV1ServerPostRequest;
import minicloud.client.model.Server;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
@Tag(name = "server", description = "Operations about the servers")
public interface ServerApi {

    /**
     * GET /api/v1/server : Get all servers
     *
     * @return Successful operation (status code 200)
     */
    @Operation(
        operationId = "apiV1ServerGet",
        summary = "Get all servers",
        tags = { "server" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful operation", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Server.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/v1/server",
        produces = { "application/json" }
    )
    ResponseEntity<List<Server>> apiV1ServerGet(
        
    );


    /**
     * DELETE /api/v1/server/{name} : Delete an existing server
     *
     * @param name Name of the server (required)
     * @return Successful operation (status code 200)
     *         or Invalid input (status code 400)
     *         or Server not found (status code 404)
     */
    @Operation(
        operationId = "apiV1ServerNameDelete",
        summary = "Delete an existing server",
        tags = { "server" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful operation"),
            @ApiResponse(responseCode = "400", description = "Invalid input"),
            @ApiResponse(responseCode = "404", description = "Server not found")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/api/v1/server/{name}"
    )
    ResponseEntity<Void> apiV1ServerNameDelete(
        @Parameter(name = "name", description = "Name of the server", required = true, in = ParameterIn.PATH) @PathVariable("name") String name
    );


    /**
     * GET /api/v1/server/{name} : Get the server
     *
     * @param name Name of the server (required)
     * @return Successful operation (status code 200)
     *         or Invalid input (status code 400)
     *         or Server not found (status code 404)
     */
    @Operation(
        operationId = "apiV1ServerNameGet",
        summary = "Get the server",
        tags = { "server" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful operation", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Server.class))
            }),
            @ApiResponse(responseCode = "400", description = "Invalid input"),
            @ApiResponse(responseCode = "404", description = "Server not found")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/v1/server/{name}",
        produces = { "application/json" }
    )
    ResponseEntity<Server> apiV1ServerNameGet(
        @Parameter(name = "name", description = "Name of the server", required = true, in = ParameterIn.PATH) @PathVariable("name") String name
    );


    /**
     * POST /api/v1/server : Create a new server
     *
     * @param apiV1ServerPostRequest Create a new server (required)
     * @return Successful operation (status code 201)
     *         or Invalid input (status code 400)
     *         or Server already exists (status code 409)
     */
    @Operation(
        operationId = "apiV1ServerPost",
        summary = "Create a new server",
        tags = { "server" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Successful operation", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Server.class))
            }),
            @ApiResponse(responseCode = "400", description = "Invalid input"),
            @ApiResponse(responseCode = "409", description = "Server already exists")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/v1/server",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<Server> apiV1ServerPost(
        @Parameter(name = "ApiV1ServerPostRequest", description = "Create a new server", required = true) @Valid @RequestBody ApiV1ServerPostRequest apiV1ServerPostRequest
    );


    /**
     * POST /server/{name}/start : Start the server
     *
     * @param name Name of the server (required)
     * @return Successful operation (status code 200)
     *         or Invalid input (status code 400)
     *         or Server not found (status code 404)
     */
    @Operation(
        operationId = "serverNameStartPost",
        summary = "Start the server",
        tags = { "server" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful operation"),
            @ApiResponse(responseCode = "400", description = "Invalid input"),
            @ApiResponse(responseCode = "404", description = "Server not found")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/server/{name}/start"
    )
    ResponseEntity<Void> serverNameStartPost(
        @Parameter(name = "name", description = "Name of the server", required = true, in = ParameterIn.PATH) @PathVariable("name") String name
    );


    /**
     * POST /server/{name}/stop : Stop the server
     *
     * @param name Name of the server (required)
     * @return Successful operation (status code 200)
     *         or Invalid input (status code 400)
     *         or Server not found (status code 404)
     */
    @Operation(
        operationId = "serverNameStopPost",
        summary = "Stop the server",
        tags = { "server" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful operation"),
            @ApiResponse(responseCode = "400", description = "Invalid input"),
            @ApiResponse(responseCode = "404", description = "Server not found")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/server/{name}/stop"
    )
    ResponseEntity<Void> serverNameStopPost(
        @Parameter(name = "name", description = "Name of the server", required = true, in = ParameterIn.PATH) @PathVariable("name") String name
    );

}
