@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package minicloud.client.template;

import core.annotation.MethodsReturnNonnullByDefault;
import core.annotation.ParametersAreNonnullByDefault;