@MethodsReturnNotNullByDefault
@ParametersAreNotNullByDefault
package minicloud.client.template;

import core.annotation.MethodsReturnNotNullByDefault;
import core.annotation.ParametersAreNotNullByDefault;