@MethodsReturnNotNullByDefault
@ParametersAreNotNullByDefault
package minicloud.api.template;

import core.annotation.MethodsReturnNotNullByDefault;
import core.annotation.ParametersAreNotNullByDefault;