@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package minicloud.api.template;

import core.annotation.MethodsReturnNonnullByDefault;
import core.annotation.ParametersAreNonnullByDefault;