/*
 * MiniCloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type ServerGroup struct {
	Name string `json:"name,omitempty"`

	Template string `json:"template,omitempty"`

	Ports []Port `json:"ports,omitempty"`

	MaxPlayersPerServer int32 `json:"max-players-per-server,omitempty"`
}

// AssertServerGroupRequired checks if the required fields are not zero-ed
func AssertServerGroupRequired(obj ServerGroup) error {
	for _, el := range obj.Ports {
		if err := AssertPortRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseServerGroupRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ServerGroup (e.g. [][]ServerGroup), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseServerGroupRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aServerGroup, ok := obj.(ServerGroup)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertServerGroupRequired(aServerGroup)
	})
}
