/*
 * MiniCloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"time"
)

type Template struct {
	Name string `json:"name,omitempty"`

	Command string `json:"command,omitempty"`

	Size int32 `json:"size,omitempty"`

	CreatedAt time.Time `json:"createdAt,omitempty"`

	UpdatedAt time.Time `json:"updatedAt,omitempty"`
}

// AssertTemplateRequired checks if the required fields are not zero-ed
func AssertTemplateRequired(obj Template) error {
	return nil
}

// AssertRecurseTemplateRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Template (e.g. [][]Template), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseTemplateRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aTemplate, ok := obj.(Template)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertTemplateRequired(aTemplate)
	})
}
