@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package net.thenextlvl.cloud.server;

import core.annotation.MethodsReturnNonnullByDefault;
import core.annotation.ParametersAreNonnullByDefault;