@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package net.thenextlvl.cloud.template;

import core.annotation.MethodsReturnNonnullByDefault;
import core.annotation.ParametersAreNonnullByDefault;