/*
 * MiniCloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

import "time"

type EventMessageObject struct {
	Name string `json:"name,omitempty"`

	Group string `json:"group,omitempty"`

	IpAddress string `json:"ip-address,omitempty"`

	// Server Status
	Status string `json:"status,omitempty"`

	OnlinePlayers int32 `json:"online-players,omitempty"`

	Command string `json:"command,omitempty"`

	Size int32 `json:"size,omitempty"`

	CreatedAt time.Time `json:"createdAt,omitempty"`

	UpdatedAt time.Time `json:"updatedAt,omitempty"`

	Template string `json:"template,omitempty"`

	Ports []Port `json:"ports,omitempty"`

	MaxPlayersPerServer int32 `json:"max-players-per-server,omitempty"`
}

// AssertEventMessageObjectRequired checks if the required fields are not zero-ed
func AssertEventMessageObjectRequired(obj EventMessageObject) error {
	for _, el := range obj.Ports {
		if err := AssertPortRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseEventMessageObjectRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of EventMessageObject (e.g. [][]EventMessageObject), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseEventMessageObjectRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aEventMessageObject, ok := obj.(EventMessageObject)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertEventMessageObjectRequired(aEventMessageObject)
	})
}
