/*
 * MiniCloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

type Port struct {
	Hostname string `json:"hostname,omitempty"`

	Protocol string `json:"protocol,omitempty"`

	TargetPort int32 `json:"target-port,omitempty"`

	PublishedPort int32 `json:"published-port,omitempty"`

	PublishMode string `json:"publish-mode,omitempty"`
}

// AssertPortRequired checks if the required fields are not zero-ed
func AssertPortRequired(obj Port) error {
	return nil
}

// AssertRecursePortRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Port (e.g. [][]Port), otherwise ErrTypeAssertionError is thrown.
func AssertRecursePortRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPort, ok := obj.(Port)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertPortRequired(aPort)
	})
}
