/*
 * MiniCloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

type CreateServerRequest struct {
	Name string `json:"name,omitempty"`
}

// AssertCreateServerRequestRequired checks if the required fields are not zero-ed
func AssertCreateServerRequestRequired(obj CreateServerRequest) error {
	return nil
}

// AssertRecurseCreateServerRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of CreateServerRequest (e.g. [][]CreateServerRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseCreateServerRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aCreateServerRequest, ok := obj.(CreateServerRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertCreateServerRequestRequired(aCreateServerRequest)
	})
}
